# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
    favicon: "https://jokers-1252021562.file.myqcloud.com/images/E331245678.png"
    high_res_favicon: "https://jokers-1252021562.file.myqcloud.com/images/E331245678.png"
    apple_touch_icon: "https://jokers-1252021562.file.myqcloud.com/images/E331245678.png"
    keywords: j3koer,java,技术,SpringBoot,SpringCloud,mysql,前端,哲学,游记,旅行
    site_verification:
        google: GR9LU1RCbNSfL3w3qoJGY5AiJDOMzPnbEKxP-GyzcZo
        baidu: aTPMu0Yaic

    # Enable generate structured-data as JSON+LD for SEO or not.
    #        Set as 'false' if it cause some wrong when `hexo g`.
    structured_data: true

# Jump Links Settings
url:
    rss: "/rss2.xml"
    daily_pic: "#"
    logo: "http://blog.csdn.net/j3oker"


# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Schemes
scheme: Paradox
#scheme: Isolation

# UI & UX: slogan, color, effect
uiux:
    slogan: "食得鹹魚抵得渴"
    theme_color: "#0097A7"
    theme_sub_color: "#00838F"
    hyperlink_color: "#00838F"
    button_color: "#212121"
    android_chrome_color: "#0097A7"
    nprogress_color: "#29d"
    nprogress_buffer: "800"

# JS Effect Switches
js_effect:
    fade: true
    smoothscroll: true

# Reading experience
reading:
    entry_excerpt: 80

# Thumbnail Settings
thumbnail:
    purecolor:
    random_amount: 19

# Background Settings
# bing available parameter:
#     new | color= | type=
#         color available value: black, blue, brown, green, multi, orange, pink, purple, red, white, yellow
#         type available value: A (animal), C (culture), N (nature), S (space), T (travel)
background:
    purecolor: "#F1F1F1"
    bgimg: "https://jokers-1252021562.cosgz.myqcloud.com/images/E7.jpg"
    bing:
        enable: false
        parameter:

# Images Settings
img:
    logo: "https://jokers-1252021562.file.myqcloud.com/images/E331245678.png"
    avatar: "https://jokers-1252021562.file.myqcloud.com/images/yu_head.jpg"
    daily_pic: "https://jokers-1252021562.file.myqcloud.com/images/E598683423E33C5EEEFC2C0AD77A24B1.jpg"
    sidebar_header: "/img/sidebar_header.png"
    random_thumbnail: "/img/random/material-"
    footer_image:
        #upyun_logo:
            #link: "https://www.upyun.com/"
            #src: "/img/upyun_logo.svg"

# Custom Fonts
#   family: the font-family which will be used in the theme
#   host: uri of fonts host.
#       Available value of "host": google | baomitu | ustc | custom
fonts:
    family: Roboto, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "微软雅黑", Arial, sans-serif
    use: google
    custom_font_host:

# Card Elevation Level
card_elevation: 2

# Copyright
# Specify the date when the site was setup.
#   For example, if you set it as 2015, then footer will show '© 2015 - 2017'
copyright_since: 2016

# Qrcode for redirect at other device
#   use: choose which method to generate the qrcode for each posts.
#       Available value of "use": plugin | online
#           - When use "plugin", you need to install the hexo-helper-qrcode.
#           - When use "online", the qrcode will be generated by 'pan.baidu.com' in China.
qrcode:
    enable: false
    use: plugin


# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

# TOC Button

toc:
#   use: choose whether the line_number of toc will show or not.
#       Available value of "linenumber": true | false
    linenumber: true

# SNS Menu
sns:
    email: yutong467942250@gmail.com
    facebook: "https://www.facebook.com/facebook"
    twitter: "https://twitter.com/twitter"
    googleplus: "https://plus.google.com/u/0/108546576810753300673"
    weibo: "https://m.weibo.cn"
    instagram:
    tumblr:
    github: "https://github.com/tong12580"
    linkedin:
    zhihu:
    bilibili:
    telegram:

# SNS Share Switch
sns_share:
    twitter: true
    facebook: true
    googleplus: true
    weibo: true
    linkedin: true
    qq: true
    telegram: true

# Sidebar Customize
sidebar:
    dropdown:
        Email Me:
            link: "mailto:yutong467942250@gmail.com"
            icon: email
    homepage:
        use: true
        icon: home
        divider: false
    archives:
        use: true
        icon: inbox
        divider: false
    categories:
        use: true
        icon: chrome_reader_mode
        divider: false
    pages:
        标签:
            link: "/tags"
            icon: stars
            divider: false
        时间轴:
            link: "/timeline"
            icon: timeline
            divider: false
        友情链接:
            link: "/links"
            icon: link
            divider: false
    article_num:
        use: false
        divider: false
    footer:
        divider: true
        theme: true
        support: false
        feedback: false
        material: false


# ---------------------------------------------------------------
# Integrated Services
# ---------------------------------------------------------------

# MaterialCDN
# When you set 'use' as true, the needed css, js, font file will have a new src.
# The new src will have the base domain you configured in 'base'.
materialcdn: 
    use: 
    base: 

# Comment Systems
# Available value of "use":
#     disqus | disqus_click | changyan | 163gentie
comment:
    use: disqus_click
    shortname: tong12580-github-io-jokers
    changyan_appid:
    changyan_conf:
    changyan_thread_key_type: path
    gentie_productKey: 

# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: google
    swiftype_key:

# Analytics Systems
# Available value:
#     baidu | google | cnzz
analytics:
    use:
    site_id:

# Leancloud Views
leancloud:
    enable: false
    app_id: #你的 app_id
    app_key: #你的 app_key
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

# Busuanzi 不蒜子 Views
busuanzi:
    enable: false
    all_site_uv: false
    post_pv: false
    busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"